reilabs/hieratika

crates/compiler/src/compile.rs
crates/rust-test-input/src/lib.rs
docs/Getting LLVM IR Output.md
flake.nix

For the current phase of work we are requiring that input LLVM IR be built to target the `aarch64-unknown-none-softfloat` target. This means that it can make no assumptions about either the host operating system (as there is none), nor the target ABI (meaning that we fall back to platform codegen ABI convention, and hence that `rustc` will not do anything funky here).
We add support in the nix derivation (`flake.nix`) so that this target is automatically made available in the sandbox. It may be necessary to add it at the system level as well, depending on how your development environment is set up.

Add support for our temporary target

---

.husky/pre-commit
flake.nix
package.json

This fixes some commands that were depending on things being in the system path and not provided by the nix development environment. It also makes the precommit hooks more efficient, now only ever running on changed files as needed.
As long as CI passes this should be good.

Make the nix stuff work reliably

---

.gitignore
lint-staged.config.mjs
package.json

It turns out that `clippy-driver` can only accept single files as input, while `lint-staged` calls by default with batches of files. This uses the JS configuration option to instead create a separate task for each Rust file that needs to be linted.
N/A

Fix the clippy check precommit hook

---

Cargo.lock
Cargo.toml
README.md
crates/README.md
crates/cli/Cargo.toml
crates/cli/README.md
crates/cli/src/main.rs
crates/compiler/Cargo.toml
crates/compiler/README.md
crates/compiler/input/add.ll
crates/compiler/src/context/mod.rs
crates/compiler/src/lib.rs
crates/compiler/src/llvm/data_layout.rs
crates/compiler/src/llvm/typesystem.rs
crates/compiler/src/pass/analysis/module_map.rs
crates/compiler/src/pass/mod.rs
crates/compiler/src/polyfill/mod.rs
crates/driver/Cargo.toml
crates/driver/README.md
crates/error/Cargo.toml
crates/error/README.md
crates/flo/Cargo.toml
crates/flo/README.md
crates/rust-test-input/Cargo.toml
docs/ALU Design.md
docs/CONTRIBUTING.md
docs/LLVM IR Generation Features.md
flake.nix
workspace.nix

As decided upon by the team, this is the official and much more catchy name for this project. The reasoning behind the choice is provided in the README.
This commit changes all references to "ltc", "llvm-to-cairo", or "LLVM to Cairo" to instead refer to the new name.
I've done my best with searches both manually and with `rg`, but please check through things to ensure there are no further references to "ltc", "llvm-to-cairo", or "LLVM to Cairo" in the codebase except where it makes sense (in the title).

Rename the project to Hieratika

---

.github/workflows/docs.yml
.github/workflows/rust.yml
crates/compiler/src/lib.rs
crates/compiler/src/llvm/data_layout.rs
crates/compiler/src/llvm/special_intrinsics.rs

This makes sure that clippy lints will cause the linting CI pipeline to fail, and also ensures the same for the newly added docs checking pipeline.
N/A

Elevate warnings to errors on CI

---

Cargo.lock
crates/flo/Cargo.toml
crates/flo/src/flo.rs

This switches from the `serde_sexpr` crate to the more up-to-date `serde-lexpr` crate.

flo: switch to more up-to-date sexpr library

---

Cargo.lock
crates/flo/Cargo.toml
crates/flo/src/builders.rs
crates/flo/src/flo.rs
crates/flo/src/types.rs
crates/flo/tests/flo_test.rs

This commit alters the `FLO` object format representation in some small ways to make it easier to build object file output in the hieratika compiler. It provides access to the context from within the builder for more in-depth modifications, and also changes the type representation subtly to make it less complex.
Just a sanity check, please!

Tweak the FLO representation for easier building

---

Cargo.lock
Cargo.toml
crates/compiler/Cargo.toml
crates/compiler/src/lib.rs
crates/compiler/src/llvm/data_layout.rs
crates/compiler/src/llvm/special_intrinsics.rs
crates/compiler/src/llvm/typesystem.rs
crates/compiler/src/obj_gen/data.rs
crates/compiler/src/obj_gen/mod.rs
crates/compiler/src/obj_gen/util.rs
crates/compiler/src/pass/analysis/module_map.rs
crates/compiler/src/polyfill/mappings.rs
crates/compiler/src/polyfill/mod.rs
crates/compiler/tests/common/mod.rs
crates/compiler/tests/compilation_basic_add.rs
crates/error/src/compile.rs
crates/flo/src/builders.rs
crates/flo/src/flo.rs
crates/flo/src/intern.rs
crates/flo/src/types.rs
crates/flo/tests/flo_test.rs
crates/rust-test-input/src/lib.rs

This commit adds the `ObjectGenerator` and the related support types, as well as performing the basic plumbing of it into the compilation flow.
It performs enough compilation to be able to compile the _most basic_ of the examples we have available, but will explicitly crash on anything else.
Anything you see fit! Please be nit-picky. There's a lot of code, and while not much of it is complicated, it is still a lot to understand all at once.

Perform partial compilation

---

crates/cairoc/src/lib.rs
crates/compiler/input/opcodes.ll
crates/compiler/src/llvm/typesystem.rs
crates/compiler/src/obj_gen/data.rs
crates/compiler/src/obj_gen/mod.rs
crates/compiler/src/obj_gen/util.rs
crates/compiler/src/polyfill/mappings.rs
crates/compiler/src/polyfill/mod.rs
crates/compiler/tests/compilation_basic_opcodes.rs

This commit also includes a re-work of how the polyfill name mapping is handled to make it easier to maintain and more robust against changes.
The usual, please.

Implement additional opcodes

---

crates/compiler/input/opcodes.ll
crates/compiler/src/lib.rs
crates/compiler/src/llvm/typesystem.rs
crates/compiler/src/messages.rs
crates/compiler/src/obj_gen/mod.rs
crates/compiler/src/obj_gen/util.rs
crates/compiler/src/polyfill.rs
crates/compiler/tests/compilation_basic_add.rs
crates/compiler/tests/compilation_basic_opcodes.rs
crates/flo/src/builders.rs
crates/flo/src/types.rs

This implements the remaining instruction opcodes that are not terminator instructions, ensuring that we have complete coverage of all non-terminator operations.
GitHub is being strange, so trying a new PR with the same content as #98.

Implement compilation of additional opcodes

---

crates/cli/src/main.rs
crates/compiler/src/lib.rs
crates/compiler/src/llvm/data_layout.rs
crates/compiler/src/llvm/typesystem.rs
crates/compiler/src/obj_gen/mod.rs
crates/flo/src/flo.rs
crates/flo/src/intern.rs
crates/flo/src/lib.rs

This means that we get a warning if anything we are expecting does not actually occur, and hence we get more feedback as to the state of our compilation and lint rules.
N/A

Use `#[expect(...)]` instead of `#[allow(...)]`

---

Cargo.lock
Cargo.toml
crates/compiler/src/llvm/typesystem.rs
crates/compiler/src/obj_gen/mod.rs
crates/compiler/src/obj_gen/util.rs
flake.nix
workspace.nix

This commit bumps our Inkwell dependency to depend on a WIP branch that adds support for LLVM 19 but without support for any of the new features that 19 comes with. This means that the version in the nix configuration is also changed.
This is done in order to support compiling to LLVM IR with the latest nightlies, which use LLVM 19 and have the most up-to-date `build-std` support.
Just a check that nothing has been changed _except_ the LLVM version. All of the tests pass as is, of course.
Work to move to the official Inkwell repo is tracked in #117.

Support LLVM 19

---

Cargo.lock
crates/compiler/Cargo.toml
crates/compiler/input/compilation/add.ll
crates/compiler/input/compilation/bad_data_layout.ll
crates/compiler/input/compilation/bad_target_triple.ll
crates/compiler/input/compilation/constants.ll
crates/compiler/input/compilation/opcodes.ll
crates/compiler/input/compilation/terminators.ll
crates/compiler/src/constant.rs
crates/compiler/src/lib.rs
crates/compiler/src/llvm/typesystem.rs
crates/compiler/src/obj_gen/data.rs
crates/compiler/src/obj_gen/mod.rs
crates/compiler/src/obj_gen/util.rs
crates/compiler/src/pass/analysis/module_map.rs
crates/compiler/src/polyfill.rs
crates/compiler/tests/bug_111.rs
crates/compiler/tests/common/mod.rs
crates/compiler/tests/compilation_alloc.rs
crates/compiler/tests/compilation_basic_add.rs
crates/compiler/tests/compilation_constants.rs
crates/compiler/tests/compilation_opcodes.rs
crates/compiler/tests/compilation_terminators.rs
crates/compiler/tests/invalid_target.rs
crates/error/src/compile/llvm.rs
crates/flo/src/types.rs

This commit uses the previously-compiled LLVM IR representations of the rust `core`, `alloc` and `compiler_builtins` libraries to test the functionality of the hieratika compiler. At the same time it fixes any bugs that are found through this process.
It also enables the compiler to consistency check the target definition in the file being compiled against the expected target definition, ensuring that it does not do unnecessary work on unsupported inputs.
It also implements functionality for working with constants of aggregate type, thereby closing #91.
Please pay careful attention to the logical changes.

Test the compiler on `core` and `alloc`

---

crates/compiler/src/llvm/typesystem.rs
crates/compiler/src/messages.rs
crates/compiler/src/obj_gen/mod.rs
crates/compiler/src/polyfill.rs
docs/Memory Model.md

Unfortunately our memory model has had to change in order to support the kinds of type punning that we see in the output of `rustc`. What this primarily means is that we have changed to a byte-addressable model, reducing overall memory usage on the Cairo VM at the cost of more computation steps.
Each machine word fits 28 bytes, along with 28 bits worth of flags for future use by the memory subsystem. These flags are not treated as part of contiguous memory.
The primary changes are:
- A swap to calculate both `size_of` and `align_of` in bytes in the LLVM type system used by the compiler. This relies on the specified data layout for accurate computation.
- Alterations to the semantics of the memory-related polyfills and opcodes to compute offsets and sizes properly using the new machinery …

Comply with the new memory model

---

crates/compiler/input/compilation/constants.ll
crates/compiler/src/obj_gen/data.rs
crates/compiler/src/obj_gen/mod.rs
crates/compiler/src/obj_gen/util.rs
crates/compiler/tests/compilation_alloc.rs
docs/Memory Model.md

Prior to this commit, global values were being allocated directly as variables of their type `T`. This is incorrect, as LLVM expects globals to be of type `ptr` with a `T` able to be loaded from it.
This commit changes the global initialization logic to comply with this requirement, allocating a pointer of the correct size and then writing the constant initializer value into that variable. This ensures that programs expecting to load from globals can now do so correctly.
It also updates the Memory Model documentation to record the solution to properly handle global pointers in Hieratika.
Check that my changes make sense to _you_ and not just me, please!

Fix the handling of global values

---

Cargo.lock
Cargo.toml
crates/error/src/lib.rs
crates/error/src/mangle.rs
crates/mangler/Cargo.toml
crates/mangler/README.md
crates/mangler/src/constants.rs
crates/mangler/src/lib.rs
crates/mangler/src/mapping.rs
crates/mangler/src/util.rs

This commit adds the `hieratika-mangler` crate, responsible for implementing the hieratika name mangling scheme in a centralized fashion.
As it exists, the name mangling scheme implemented is _not final_, and is likely to change and evolve as the requirements are clarified. To that end, the mangling design docs have not been updated, as no coherent design process has yet taken place for the mangling scheme.
Check it makes sense, please and thank you!

Implement a prototype name mangler

---

Cargo.toml
crates/compiler/input/compilation/phi.ll
crates/compiler/src/llvm/data_layout.rs
crates/compiler/src/llvm/typesystem.rs
crates/compiler/src/obj_gen/data.rs
crates/compiler/src/obj_gen/mod.rs
crates/compiler/src/obj_gen/util.rs
crates/compiler/src/polyfill.rs
crates/compiler/tests/compilation_alloc.rs
crates/compiler/tests/compilation_core.rs
crates/compiler/tests/compilation_phi.rs
crates/flo/src/types.rs
crates/mangler/src/mapping.rs

This commit is a grab-bag of smaller fixes required to get Rust's `core` library compiling properly by hieratika. They include:
- Adding support for an `i48` type which seems to be required, as well as adding polyfill stubs for such a type.
- Adding support for an `i40` type which seems to be required, as well as adding polyfill stubs for such a type.
- Changing the `DataLayout` type's query functionality to comply with the layout promotion rules for integers.
- Registers all variables inside a function ahead of time to cope with usages before declaration in lexical order but not in execution order.
- Changes the handling of GetElementPtr instructions to account for negative indices, which were not apparently allowed from the LangRef, but are encountered in `core`. As GetElementPtr does …

Make some initial fixes get `core` compiling

---

Cargo.lock
crates/compiler/Cargo.toml
crates/compiler/input/pass/declared_polyfill_bad_type.ll
crates/compiler/input/pass/declared_polyfill_correct_type.ll
crates/compiler/input/pass/redefined_polyfill.ll
crates/compiler/src/config.rs
crates/compiler/src/lib.rs
crates/compiler/src/messages.rs
crates/compiler/src/pass/analysis/module_map.rs
crates/compiler/src/pass/check/mod.rs
crates/compiler/src/pass/check/polyfill_redefinitions.rs
crates/compiler/src/pass/data.rs
crates/compiler/src/pass/mod.rs
crates/compiler/src/polyfill.rs
crates/error/src/compile/llvm.rs

This commit adds a pass that prohibits user code from redefining polyfills. This is necessary as the actual polyfill names differ from the opcodes used in LLVM, and hence redefining them needs to be explicitly disallowed.
This is done using a check pass that runs after the module mapping pass and uses the module map to check for user-defined functions that clash with the polyfill names. Note that _declaring_ the polyfills is explicitly allowed in the case that users want to call them directly.
It also fixes a bug where multiple potential polyfills would end up with clashing names. It does this by switching the polyfill naming scheme to instead use the mangler for the types it embeds in the name. This means we can always generate valid names while also including return type information for …

Disallow redefining polyfills

---

deny.toml

This change adds the `paste` library to the list of ignored warnings from `cargo deny check`.
The `paste` library has been marked as unmaintained, this causes the `cargo deny check` to fail. However, this library is currently used by the crate `cairo-lang-runner`, therefore it's out of our control. An exception is the best immediate way forward and a related ticket has been opened for future tracking of this.

Added `paste` library to `deny.toml`

---

crates/compiler/src/llvm/typesystem.rs
crates/compiler/src/obj_gen/mod.rs

Previously we were not sure whether we would have a bit-addressable or byte-addressable memory. Now we have made the decision to keep it to the latter, we want to talk about offsets and sizes in bytes instead of bits.
To this end, this PR adds implementations of `size_of` and co that return bytes, in addition to the existing ones in bits, and updates the compiler to call the byte-oriented methods instead where relevant.
It's a very simple change, but required reading a bunch of the memory-related code to check things.

Operate over memory in bytes

---

crates/compiler/src/llvm/typesystem.rs

This PR updates the function `is_integral` to include additional integer types.

Updated function `is_integral` to include new integer types

---

.gitignore
Cargo.lock
Cargo.toml
crates/cairoc/src/export/lowered.rs
crates/cairoc/src/lib.rs
crates/cli/Cargo.toml
crates/cli/src/args.rs
crates/cli/src/main.rs
crates/cli/tests/hieratika_cli_error_output.rs
crates/cli/tests/hieratika_cli_warning_output.rs
crates/error/src/compile/cairo.rs
crates/flo/src/intern.rs
crates/flo/src/types.rs
crates/lifter/Cargo.toml
crates/lifter/README.md
crates/lifter/src/builder.rs
crates/lifter/src/lib.rs
crates/mangler/src/constants.rs
crates/mangler/src/mapping.rs

This adds a fairly complete lifter capable of re-representing Cairo FlatLowered code as FLO objects, which can then be e.g. linked together with other FLO objects -- including ones taken from Cairo.
There are currently two major limitations on this: a limited number of cairo interface types are supported (primarily, things like Coupons, and things that deal with Impls are missing), and this commit lacks support for lifting Match expressions, which will come in a commit to follow to avoid introducing any real compiler changes in the main lifter commit.
This is a re-push of an already-approved PR, and will be self-merged. :scream: :

Add a Cairo -> FlatLoweredObject lifter.

---

compiler-rt/src/integer.cairo
compiler-rt/src/integer/u24.cairo
compiler-rt/src/integer/u40.cairo

This type serves as a backing for our `i24` polyfill operations by implementing the behavior required of a primitive integer in Cairo.
Additionally, it adds the `IntegerOps` trait that all of these non-standard integers should implement, as well as refactors `u40` to use that operation as well.
Check that things make sense, as ever! This implements the backing type for #155, but none of the actual polyfill operations.

Implement the `u24` type

---

compiler-rt/src/integer.cairo
compiler-rt/src/integer/u48.cairo

This type serves as a backing for our `i48` polyfill operations by implementing the behavior required of a primitive integer in Cairo.
N/A

Implement the `u48` type

---

Cargo.lock
Cargo.toml
compiler-rt/Scarb.toml
compiler-rt/cairo_project.toml
crates/cairoc/Cargo.toml
crates/cairoc/src/lib.rs
crates/compiler/src/polyfill.rs

This adds a test that checks that the `cairoc` crate—the hieratika project's driver for the cairo compiler—is capable of compiling the `compiler-rt` project containing our polyfill definitions.
There are also some miscellaneous cleanups of the `Cargo.toml` dependencies to keep things in the minimally-required set of deps to compile.

Ensure that hieratika-cairoc compiles compiler-rt

---

Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/compiler/Cargo.toml
crates/compiler/src/llvm/data_layout.rs
crates/compiler/src/obj_gen/mod.rs
crates/compiler/src/parser/block_address.rs
crates/compiler/src/parser/constant_expr.rs
crates/compiler/src/parser/integer_constant.rs
crates/compiler/src/parser/inttoptr_constant.rs
crates/compiler/src/parser/mod.rs
crates/compiler/src/parser/number.rs
crates/compiler/src/parser/ptrtoint_constant.rs
crates/compiler/src/parser/typ.rs
crates/lifter/Cargo.toml

This commit updates the project's dependencies across all the crates to the latest versions unless otherwise noted.
This involves a re-write of the components that rely on Chumsky, as the crate's interface has been re-written for the 0.10.0 release. When writing the parsing sections, it was incorrect to depend on the 0.9.0 release as this was old and not a reflection of modern parsing practice. This upgrade fixes this oversight, and also improves parsing speed.
The parser changes should be very minor, even though a reasonable number of lines have changed. Please carefully check for anything that shoudl change semantics.

Bump project dependencies

---

Cargo.lock
crates/compiler/build.rs
crates/lifter/src/builder.rs
deny.toml
flake.lock

We want to keep up with Cairo releases, and we are a bit behind, so this bumps us from 2.10.x to 2.11.2. It makes some minor changes to the codebase in order to comply, as well as some minor changes to the build system (`build.rs` and the nix definitions) to make things more predictable in the build.
N/A

Update the version of cairo

---

.github/workflows/rust.yml
crates/compiler/build.rs
crates/compiler/src/llvm/data_layout.rs
crates/compiler/src/llvm/special_intrinsics.rs
crates/compiler/src/llvm/typesystem.rs
crates/compiler/src/obj_gen/data.rs
crates/compiler/src/obj_gen/mod.rs
crates/compiler/src/parser/block_address.rs
crates/compiler/src/parser/constant_expr.rs
crates/compiler/src/parser/getelementptr_constant.rs
crates/compiler/src/parser/inttoptr_constant.rs
crates/compiler/src/parser/mod.rs
crates/compiler/src/parser/ptrtoint_constant.rs
crates/compiler/src/parser/typ.rs
crates/compiler/src/pass/analysis/module_map.rs
crates/compiler/src/polyfill.rs
crates/compiler/tests/compilation_alloc.rs
crates/compiler/tests/compilation_compiler_builtins.rs
crates/compiler/tests/compilation_core.rs
crates/flo/src/types.rs
crates/flo/tests/flo_test.rs
crates/mangler/src/mapping.rs
flake.lock
tests/rust-test-input/package.nix

This commit bumps the version of the nightly compiler used to build the Rust core libraries. In doing so, a missing feature was discovered in the hieratika compiler.
To ensure that `core` and `compiler_builtins` continue to compile, support was implemented for `getelementptr` constant expressions in the compiler, ensuring that the project is not incompatible with newer versions of `rustc`.
As part of this work, we clarify the implementation of GEP to allow for negative offsets in arrays and from base pointers, which is supported by the spec.
Please carefully read the GEP stuff.

Update the nightly compiler

---

.github/workflows/docs.yml
Cargo.toml
crates/cairoc/src/lib.rs
crates/cli/src/main.rs
crates/compiler/src/llvm/data_layout.rs
crates/compiler/src/obj_gen/mod.rs
crates/flo/src/builders.rs
flake.nix

I originally thought that this was required for bumping inkwell to 0.6.0 as an official version with LLVM 19 support, but I had misread the release notes and there is still no official LLVM 19 support. Still, the work was done, so I might as well PR it.
N/A

Bump rustc to 1.86.0

---

Cargo.lock
Cargo.toml
crates/compiler/Cargo.toml
crates/compiler/src/obj_gen/data.rs
crates/mangler/Cargo.toml
crates/mangler/src/constants.rs
crates/mangler/src/lib.rs

The previous mangling scheme was intended to operate purely in FLO and Sierra which do not have any care for the way things are named. In the interests of boxing the work to getting something running, we are instead hoping to target source Cairo, which requires our naming scheme to be compatible with Cairo names. This new mangling scheme accounts for that case.
Please do suggest a better idea for replacing invalid characters. The current `_IC_` is very ugly. `___` for separation is pretty ugly too.

Add a Cairo-compatible mangling scheme
